import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

const colorPrimaryDark = Color(0xff455a64);
const colorPrimaryLight = Color(0xffcfd8dc);
const colorPrimary = Color(0xff607d8b);
const colorPrimaryText = Color(0xffffffff);
final Future<FirebaseApp> firebaseInitialization = Firebase.initializeApp();

const List<String> daftarKolom = [
  "No",
  "Jam\nMulai",
  "Jam\nSelesai",
  "Part No",
  "Lot No",
  "Qty\nCheck",
  "Qty\nOK",
  "Qty\nNG",
  "Scratch",
  "Spiral",
  "Dented",
  "Dimens",
  "Pin\nG",
  "CG",
  "Piptil",
  "Chip",
  "Shortcut",
  "Burry",
  "M\nProses",
  "Pinhole",
  "Bending",
  "Rusty",
  "Colour",
  "keterangan",
];
const List<String> daftarKolomRow = [
  "",
  "jam_mulai",
  "jam_selesai",
  "part_no",
  "lot_no",
  "qty_check",
  "qty_ok",
  "qty_ng",
  "ngns_scratch",
  "ngns_spiral",
  "ngns_dented",
  "ngns_dimens",
  "ngns_pin_g",
  "ngns_cg",
  "ngns_piptil",
  "ngns_chip",
  "ngns_shortcut",
  "ngns_burry",
  "ngns_mproses",
  "ngm_pinhole",
  "ngm_bending",
  "ngm_rusty",
  "ngm_colour",
  "keterangan",
];

List<String> listNama  = [
  "Ambar Afriyani",
  "Ana Febrina",
  "Arif Rahman",
  "Audia Awali",
  "Ayu Ratna Ningsih",
  "Azuardi",
  "Basyarani Ursha",
  "Binah",
  "Bovi Ferdiansa",
  "Diyan Supriyadi",
  "Endang Trimurtini",
  "Erna Diana Astuti",
  "Ery Safitri",
  "Etik Lestari",
  "Fauziarti",
  "Fika Dian Pratami",
  "Fitri Rahmawati",
  "Ikhda Fitrotunnisa",
  "Irma Ayu Santika",
  "Jesi Nur Rochmawati",
  "Junita",
  "Justiawan Indra Atmaja",
  "Kokok Susilo",
  "Lia Yunita",
  "Lilis Handayani",
  "Mad Saefurohman",
  "Malahayati",
  "Mayasari",
  "Muki",
  "Muslimatun",
  "Nanditha Shendi Thriziska",
  "Novan Wicaksono",
  "Novi Dwi Santoso",
  "Novi Sari Handayani",
  "Novi Utami",
  "Novia Tri Handayani",
  "Nurhidayatul Laili",
  "Nuril Amelia",
  "Nurul Alfiyani",
  "Nurul Komariyah",
  "Nuswantari",
  "Oktivianne Nurertha K",
  "Puji Rahayu",
  "Rani Riswanti",
  "Rifani Madjid",
  "Rikha Susanti",
  "Rinna Untari",
  "Riyana",
  "Rizka Novining Dias",
  "Romasti Naomi Hutauruk",
  "Rosimah",
  "Rosinih",
  "Rully Hendriyanto",
  "Siti Aliyah",
  "Siti Aulia Yulistia",
  "Siti Jamangatun",
  "Siti Kartini",
  "Siti Rifa'atul H",
  "Soleh Ibnu",
  "Sri Sulastri",
  "Susi Listiani",
  "Suyatno Surtana",
  "Tri Kuati",
  "Tutut Rizki Pramudita",
  "Uki Indra Perwitasari",
  "Wahyu Deriana",
  "Wahyu Setiadi",
  "Weni Rezeki",
  "Wiji Lestari",
  "Yana Suryana",
  "Yohanes Alferdo Oktama",
  "Yustina Widhianti"
];

List<String> listPartnumber = [
  '1466273-00-A01',
  '1477428-00-A01',
  '1477429-00-A01',
  '168856-00-A01',
  '1705171-01-A01'];

List<String> listLotnumber = [
  '22810N077200',
  '22810N078200',
  '22810N080200',
];